registration:
    path: /register
    controller: App\Controller\SecurityController::register

login:
    path: /login
    controller: App\Controller\SecurityController::login

home:
    path: /
    controller: App\Controller\SecurityController::register